### PR TITLE
[DO NOT MERGE][REFERENCE]honami: update thermanager

### PR DESCRIPTION
**Pull request by alviteri**
spmi driver was updated .. update thermanager to match new sysfs path names

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by AdFad666** [comment]
oh wow I did not know rhine was still using these wrong paths. They need to be rewritten to use sys/class/thermal like all other platforms!

**Comment by alviteri** [comment]
Go ahead Adam :)

**Comment by AdFad666** [comment]
Rhine ADB is still death last time I checked.

**Comment by alviteri** [comment]
My honami has adb working here

**Pull request closed without merging**
